PistonDevelopers/glfw-rs

- examples/error.rs
- src/callbacks.rs
- src/lib.rs
Fixes breakages after changes to C string handling and the switch to unboxed closures in the last couple Rust nightlies.
Compiles and tests successfully as of the opening of this PR. I ignored the warnings for missing `Copy` implementations as I figured making certain structs `Copy` within the `ffi` module merited some discussion.
> Update to latest Rust nightly

- examples/error.rs
- src/callbacks.rs
- src/ffi/mod.rs
- src/lib.rs
- Remove use of markers
- use slice::from_raw_buf instead of vec::Vec::from_raw_buf (safer life times)
- get_gamma_ramp had a questionable conversion to a Vec.
> Minor cleanup

- examples/modes.rs
- examples/monitors.rs
- src/lib.rs
The apis that query the monitors are no longer useful, since you cannot take
a &mut Glfw if it is already borrowed as &Glfw. So you could query the screens,
but the value was useless when it came to actually creating a window with a screen.
> As a fallout of the mutability change some apis need to be tweaked.

- README.md
Fix the example code in README similar to what commit bc1b352 ("Fix
unwrap in examples") did for the examples.
Signed-off-by: Pekka Enberg <penberg@iki.fi>
> Fix unwrap in example code in README

- examples/clipboard.rs
- examples/cursor.rs
- examples/defaults.rs
- examples/error.rs
- examples/events.rs
- examples/modes.rs
- examples/monitors.rs
- examples/render_task.rs
- examples/title.rs
- examples/window.rs
- src/lib.rs
Revert change to use .ok().except(...)
In response to @tomaka's comment on https://github.com/bjz/glfw-rs/pull/280#issuecomment-71368742.
> Use fmt::Display in InitError.

- README.md
Revert "Fix unwrap in example code in README"
This reverts commit 47906f8160e3035fc1a5dc27c8335b5c8ad2f6bd.
> Missed in #282.

- src/callbacks.rs
Removed the last usage of the old box syntax.
This fixes the build on the current nightly (2015-03-07) without requiring the feature gate to be enabled.
> Removed usage of the old box syntax.

- src/ffi/mod.rs
- src/lib.rs
This fixes compilation on nightly. Unfortunately there's still a couple feature gates (`core` and `std_misc`) which I don't know replacements for, so it won't work in beta.
There's a couple new warnings about the use of #[derive] with a raw pointer; I'm not sure if that's actually a problem.
> Update for latest rust

- src/lib.rs
As discussed in #306, this is a fix for naming. It was decided that we would use `OpenGl` and `OpenGlEs`.
> Modifications for more consistent naming

- src/lib.rs
removes derive FromPrimitive from enums which doesn't exist anymore and a deprecated function since the deprecation mechanism cannot be used outside of the std now
> fixes for latest rust

- src/ffi/link.rs
This has been tested on DragonFly BSD.
It is assumed to be the same on FreeBSD and many other BSDs which
use X11.
> Also link to libraries on other systems

- Cargo.toml
- src/lib.rs
Re-implements the functionality removed in #314 due to FromPrimitive being removed. This uses the `num` crate's FromPrimitive trait, along with [enum_primitive](https://andersk.github.io/enum_primitive-rs/enum_primitive/), to implement it in a more stable way.
> Re-add support for FromPrimitive, in a non-deprecated way.

- examples/multiwindow.rs
- src/lib.rs
... and reordered the implementation of Window::drop to prevent a memory error.
To demonstrate the issue (and the fix), also added an example for managing multiple windows.
> Fixed a logic error preventing windows from being destroyed

- src/ffi/link.rs
GLFW when compiled on Unix-like systems as shared lib is named glfw, not glfw3. Fix #292.
> Fix linking to wrong library on Unix-like systems (#292)

- examples/events.rs
- src/callbacks.rs
- src/lib.rs
Registers the drag and drop callback optionally when calling set_drag_and_drop_polling and adds a new event: Dropped(Vec<PathBuf>)
Because of the new event, WindowEvent can't be Copy anynmore which might break some code
> Add support for drag and drop

- .travis.yml
- README.md
Resolves #369.
An overview of the changes made:
The error `E: Unable to locate package libXxf86vm-dev` occurs because there is a typo in the package name, the correct name of the package is `libxxf86vm-dev` (lower case x). In any case, this package is installed by default in Trusty so I removed it.
The build was running into problems with a CMake build which stated that `The RandR library and headers were not found`. After looking [here](https://github.com/openMVG/openMVG/issues/85), this was resolved by installing the `xorg-dev` and  `libglu1-mesa-dev`, but since the latter is already installed in Trusty I just added the former.
CMake is now at 3.2.2 in Trusty and installed by default so I removed this package from the list that are installed.
In summary, the dependencies added are:
- …
> Fix Travis CI build and clean up

- Cargo.toml
- examples/clipboard.rs
- src/callbacks.rs
- src/lib.rs
- Updated dependencies
- Moved `Modifiers` one level up because variants in bitflags 1.0.0 are
in namespace `Modifiers`
> Published 0.19.0

- src/lib.rs
This hint [has existed for some time](https://github.com/glfw/glfw/blob/089ea9af227fdffdf872348923e1c12682e63029/docs/news.dox#L322) but somehow was forgotten in glfw-rs. This commit just adds that.
> Add forgotten Focused hint

- Cargo.toml
- src/lib.rs
Hi there! I recently ran into a problem using `glfw-rs` in a Rust library called from a Mac App. My solution necessitated being able to manually terminate the GLFW library. After adding the feature in my own fork, I figured I'd share it back in case you'd like to incorporate it.
When making a Mac App, Apple's AppKit creates its own `NSAutoreleasePool` object to manage autoreleased Objective-C objects. The underlying GLFW C library creates its own `NSAutoreleasePool` objects as well.  As it is right now, using `glfw-rs` from an AppKit app on the main thread crashes, due to the way these two sets of `NSAutoreleasePool` objects interact.
The problem is that `NSAutoreleasePool` objects must be strictly nested inside of each other per-thread. So, for example, it will crash if you create Pool …
> Added the ability to terminate GLFW manually

- Cargo.toml
- src/lib.rs
`key_name(key: Option<Key>, scancode: Option<Scancode>) -> String` and its associated wrapper method `Key::name(&self) -> String` can cause a segmentation fault (crashing the program without useful information), as it does not take into account the behaviour of  `const char* glfwGetKeyName( int key, int scancode)`.
`glfwGetKeyName()` returns a null pointer many inputs, such as SHIFT or SPACE. Quoting from [the GLFW3 doc for glfwGetKeyName](http://www.glfw.org/docs/latest/group__input.html#ga237a182e5ec0b21ce64543f3b5e7e2be)...
> If a non-printable key or (if the key is GLFW_KEY_UNKNOWN) a scancode that maps to a non-printable key is specified, this function returns NULL.
View the given for a list of "printable keys".
The current code will try and dereference a null pointer inside of …
> key_name() and name() cause segfaults, add safe functions

- src/ffi/link.rs
shell32 is no longer implicitly linked by rustc.
https://github.com/rust-lang/rust/issues/56839
> Link shell32 on windows

- examples/clipboard.rs
- examples/fullscreen.rs
- src/lib.rs
This PR changes the return type of some wrapper functions from `String` to `Option<String>` as the underlying glfw function may return a null pointer. This is now handled correctly by returning a `None` using the new `string_from_nullable_c_str` helper function.
> Handle null pointers returned by glfw correctly

- Cargo.toml
- examples/events.rs
- src/callbacks.rs
- src/ffi/mod.rs
- src/lib.rs
This PR updates the `glfw-rs` library to use glfw 3.3. As such, it is dependent on PistonDevelopers/glfw-sys#12 to be merged.
This is still a WIP, most new functions still have to be implemented.
> Update for glfw 3.3

- src/ffi/link.rs
GLFW now loads these dynamically and they no longer need to be explicitly linked. 
https://www.glfw.org/docs/latest/compile_guide.html#compile_deps_x11
https://www.glfw.org/docs/latest/build_guide.html#build_link_pkgconfig
https://github.com/glfw/glfw/blob/51bb76c7c3de934b2dd3affcdc297a32e4817835/src/x11_init.c#L468
https://github.com/glfw/glfw/blob/master/src/glx_context.c#L253
```
$ PKG_CONFIG_PATH=. pkg-config --libs --static glfw3
-L/home/ci/git/glfw-rs/target/debug/build/glfw-sys-34282c5bfb8321b7/out/lib -lglfw3 -lrt -lm -ldl -lX11 -lpthread -lxcb -lXau -lXdmcp
```
> Remove link libraries that are no longer required on linux

- Cargo.toml
- src/lib.rs
Depending on these packages brings in 9 dependencies in total, including num-complex and num-rational, and adds ~50% to compile times for me (33s up to 49s for release builds). This doesn't seem worth it to me (although I'm willing to change my mind, or write a replacement, if others disagree).
> Remove dependencies on enum_primitive and num

- src/lib.rs
Looks like this was missed from #398. Attempting to set the context with vulkan results in a GLFW error (because the context client is set to GLFW_NO_API).
https://github.com/glfw/glfw/blob/master/src/context.c#L613
> Remove context check for get_instance_proc_address

- examples/unbuffered_events.rs
- src/callbacks.rs
- src/lib.rs
* Unbuffered event polling allows for event interception and response on the main thread inside of the native GLFW callback. This can be especially helpful in multi-threaded scenarios when there's a desire to intercept the `Close` request. Another use-case is when `FramebufferSize` events should be responded to synchronously to enable smoother resizing (e.g. when resizing a Vulkan Swapchain on Windows).
* Added remaining thread-safe functions to Context and by extension RenderContext.
> Add unbuffered event handling variants for `poll_events` and `wait_events`

- src/callbacks.rs
- src/lib.rs
`ONCE_INIT` has been replaced with `Once::new()`, and trait objects should be marked `dyn`.
> Fix warnings from nightly 1.38.0

- Cargo.toml
- examples/raw_window_handle.rs
- src/lib.rs
This PR adds support for [raw-window-handle](https://github.com/rust-windowing/raw-window-handle), which aims to reduce the coupling between window libraries and graphics libraries. More information can be found in the [rust-gamedev working group issue](https://github.com/rust-gamedev/wg/issues/26).
I've tested the changes in Linux and Windows and verified that they compile on MacOS (via ci). I'm fairly confident that the MacOS implementation is correct, but I don't have any means to test it myself.
> Add support for raw-window-handle

- src/lib.rs
Currently, glfw::init() is not callable twice, regardless glfw::terminate() is called or not.
This PR changes implementation of init()'s duplicate call condition.
> glfw::init() is now re-entrant after glfw::terminate()

- Cargo.toml
- src/lib.rs
Now `struct Glfw` impl `Drop` For safe GLFW termination.
It occurs following interface changes:
- Glfw is now not impl `Copy`
- Joystick is now not impl `Copy`
You should use explicit clone() when copy these marker objects.
And `manually_termination` feature is dropped. Because we can `glfwTerminate()` by Dropping Glfw marker object.
FYI: This is discussed on https://github.com/PistonDevelopers/glfw-rs/pull/428
> implement Drop for Glfw for safe termination

- Cargo.toml
- examples/raw_window_handle.rs
- src/lib.rs
The `raw-window-handle` crate has seen some breaking changes which prevent this crate from being used elsewhere in the ecosystem right now (i.e. with the latest version of `gfx-hal`).
This PR updates the dependency to 0.3 in the crate manifest and replaces usages of `RawWindowHandle::X11` and `X11Handle` with `RawWindowHandle::Xlib` and `XlibHandle` respectively. The code is otherwise identical except for these name changes.
> Update to raw-window-handle 0.3

- Cargo.toml
- src/lib.rs
This field previously defaulted to a null pointer because of `..WindowsHandle::empty()`. It is described here: https://github.com/rust-windowing/raw-window-handle/issues/2. Let me know what you think.
> Add `hinstance` field to `WindowsHandle`

- src/lib.rs
This changes the arguments of `set_size_limits` from `u32` to `Option<u32>`, with `None` being the equivalent of `ffi::DONT_CARE`.
**This is a breaking change.** Please let me know if you'd like me to change that (or anything else). Thanks!
> Allow DONT_CARE in window size limits

- src/lib.rs
Just to preface. I didn't find any notes about minimum supported Rust version, so I just want to point-out that `#[non_exhaustive]` was included in [stable release 1.40.0](https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html#[non_exhaustive]-structs,-enums,-and-variants) ([RFC](https://github.com/rust-lang/rfcs/blob/master/text/2008-non-exhaustive.md#unit-structs)).
-----
The change is simple, I added `#[non_exhaustive]` to `Glfw`.
```rust
#[non_exhaustive]
pub struct Glfw;
```
Which prevents instantiation of `Glfw`, like this:
```
let glfw = Glfw;
```
Producing the following error instead:
```
error[E0423]: expected value, found struct `Glfw`                                                   
--> app\src\app.rs:59:32
|
59 |                     let glfw = Glfw;
| …
```
> Prevent direct instantiation of Glfw leading to panic

- src/lib.rs
This pull request adds missing wrapper for `glfwCreateWindowSurface`, which is required for Vulkan applications.
> Add missing wrapper for `glfwCreateWindowSurface`

- src/lib.rs
Another small change, which fixes a panic.
For years I've had a `Window` wrapper around `glfw::Window`, with some various added metadata, which boils down to:
```rust
pub struct Window {
window: glfw::Window,
}
```
Today, I just started using `set_cursor`, e.g.
```rust
window.set_cursor(Some(Cursor::standard(StandardCursor::Hand)));
```
But when closing the program, then the program panicked:
```
thread 'main' panicked at 'GLFW Error: The GLFW library is not initialized', 
C:\Users\Vallentin\Desktop\glfw-rs\src\lib.rs:432:5
```
I realized that since I didn't keep a `Glfw` around, that when `glfw::Window` is being dropped, it first drops its `Glfw` causing GLFW to get terminated. Then after it attempts to destroy the `Cursor`, which then triggers the "GLFW not initialized".
-----
A …
> Fixed drop order causing panic

- src/lib.rs
Got patched:
- `InitError`.
- `Error`.
Those were removed in 087fc4bf7c7e441f460f0334521827be17122f7a.
Fixes #456.
> Re-introduce std::error::Error implementors.

- src/lib.rs
Hello, 
the current implementation of `update_gamepad_mappings` causes a segmentation fault on my system when called with a string containing the entire `gamecontrollerdb.txt` file. I believe the reason for that is that `ptr` is dangling.
I replaced the code using `with_c_str`, which does not cause a segmentation fault anymore and seems to be the proper tool for that.
> Fix update_gamepad_mappings

- Cargo.toml
- examples/defaults.rs
- src/callbacks.rs
- src/ffi/mod.rs
- src/lib.rs
The libc dependency is unnecessary since these aliases are already found in the standard library.
> Remove libc dependency in favor of std::os::raw aliases

- src/lib.rs
Derive `Debug` for `Window`, `Glfw` and `Cursor`.
> Derive Debug for Window.

- Cargo.toml
- src/lib.rs
I have noticed that removing log crate, reduces the binary size:
with all features disabled using the current crate:
```
[dependencies]
glfw = { version = "0.41.0", features = [], default-features = false }
```
the size of multiwindow example: 355K
With the new version with log as optional the size goes down to 331K
> Make log optional to reduce binary size

- examples/fullscreen.rs
- src/lib.rs
Closes https://github.com/PistonDevelopers/glfw-rs/issues/478
- Changing `with_...` methods to `FnOnce` whenever possible
- Remove `with_..._mut` methods since the ones with `FnOnce` can be used instead
> Use `FnOnce` trait

- README.md
Use shields.io to render version on crates.io badge.
> Fix crates.io badge in README.

- Cargo.toml
- src/lib.rs
We were depending on an old version and none of the parsing or version comparison methods were even utilized.
> Remove dependency on semver

- Cargo.toml
- src/ffi/link.rs
Adds support to glfw-rs to link against wayland-client instead of just X11, using a "wayland" feature flag. Relies on https://github.com/PistonDevelopers/glfw-sys/pull/19
Resolves https://github.com/PistonDevelopers/glfw-rs/issues/485
> Adds wayland support to glfw-rs

- README.md
Removes the usage for `--static` from OSX example due to its
deprecation from Homebrew. Running `brew install --static glfw3`
would result on `Error: invalid option: --static`.
> fix: brew `--static` no longer valid

- Cargo.toml
- examples/vulkan.rs
- src/ffi/mod.rs
- src/lib.rs
This commit removes the deprecated `vk-sys` crate in favor of the `ash` crate, supplied by [ash-rs/ash](https://github.com/ash-rs/ash).
Note `ash` does not strictly practice semver, and breaking changes can occur between patches, so a direct version dependency was made.
This closes #496
> Remove deprecated vk-sys

- src/lib.rs
not much really, just adds emscripten support to allow compilation for `wasm32-unknown-emscripten` target.
> add emscripten support

- src/lib.rs
Fixes #523
I commented on both #523 and #473. In #473 `Glfw` was made non-send, which rendered `post_empty_event()` useless, as it would no longer be possible to pass a clone of `Glfw` to a thread, to call `glfw.post_empty_event()`. Alternatively requiring doing the following instead:
```rust
unsafe {
glfw::ffi::glfwPostEmptyEvent();
}
```
However, as far as I know and can tell from reading the C source, there is no need to require `&mut self`. It should be safe to call `Glfw::post_empty_event()` before GLFW has been initialized as well as after GLFW has been terminated. As far as I can tell, is that calling it before GLFW has been initialized, it might not trigger any event. Though that sounds like an edge case to me.
In my opinion, it's better to have it usable. Maybe adding a note …
> Removed &mut self from post_empty_event fn

- src/lib.rs
Added wrappers for `glfwGetPrimaryMonitor` and `glfwGetWindowMonitor` to the `Monitor` struct. This fixes #517
> Fixes #517

- src/lib.rs
Added wrapper for `GLFW_MAXIMIZED` window hint. This fixes #499
> Add maximized window hint

- src/lib.rs
This is necessary to set the gamma of monitors while iterating over them for example.
> with_*_monitor functions now pass the monitor as a mutable reference

- Cargo.toml
- src/lib.rs
Window callbacks were previously behind a feature gate because the implementation i wrote was inherently unsafe. This was because the user could move the window object out of the `Box` after creating the window, and this would break the new callback code that requires the window pointer to never change. It just occurred to me to wrap the `Box<Window>` inside a struct `PWindow` with its own `Deref` and `DerefMut` implementations, preventing the user from taking the window out of the wrapper. This effectively stabilizes the new callback implementation so i removed the "glfw-callbacks" feature from Cargo.toml. Let me know if there is any problem, even tho i tested it and it seems to work.
> Stabilized window callbacks

- src/lib.rs
Original problem + my solution from a previous post:
I discovered a memory issue regarding the use of channels. Basically every kind of callback that uses polling will cause an allocation (window resizing events, mouse enter and exit events, etc...) and a subsequent deallocation. The solution i implemented was a custom channel type which i called `GlfwSender` / `GlfwReceiver` that internally uses a `VecDeque` in order to avoid frequent allocations. One last adjustment i made is that if the `GlfwReceiver` queue goes beyond a certain size, in order not to allocate too much memory for the `VecDeque`, it will fall back to normal mpsc channels. I initially configured the initial `VecDeque` capacity to be `16` and the maximum to be `256`, after which mpsc channels will be used until new space …
> Added GlfwSender and GlfwReceiver instead of mpsc channels

- README.md
The code example has an issue where the string "FAIL_ON_ERRORS" on line six is apparently falsely capitalized.
> Update README.md to fix issue #558

- Cargo.toml
- examples/raw_window_handle.rs
- examples/render_task.rs
- src/lib.rs
This adds the necessary features to support safe surface creation (gfx-rs/wgpu#4597) by upgrading raw-window-handle to v0.6.0, and adding a boxed render context (named PRenderContext), as this makes the new raw-window-handle default (which is different from v0.5) this is a **breaking change**.
closes #562 
Currently tested on Windows with both wgpu and the raw-window-handle example and tested on Linux (xlib handle) with raw_window_handle example
**todo:**
- Maybe testing on Emscriptem? (not sure I need this as emsciptem is unchanged)
> Upgrade GLFW for Wgpu safe surface creation

- Cargo.toml
- src/lib.rs
[`objc2`](https://github.com/madsmtm/objc2) is a replacement for `objc` that contains a bunch of safety and performance improvements, including `Id` and `msg_send_id!` which automatically upholds memory management rules.
Specifically for glfw-rs, this is likely ever so slightly faster, as the message sending can be done without needing to put the view into an autorelease pool.
Note: We could've used `objc2-app-kit` to avoid the manual `msg_send_id!` here, but the extra dependency seemed excessive.
> Use `objc2`

- src/lib.rs
`NonNull::new` returns an option. Assert that we do get a window surface as WaylandWindowHandle expects a NonNull.
> fix: Expect that wayland surface is non null

- src/lib.rs
Forgot to handle other Wayland stuff relating to raw-window-handle 0.6. This should fix the errors from compiling with default features and wayland feature on.
> Fix: raw-window-handle 0.6's Wayland api has different params

- Cargo.toml
- README.md
- src/lib.rs
Cargo docs seems to only point on making a new crate flag for this option. <br>
Semantics of this right now is we have raw-window-handle v0.6 as default. To use v0.5, one has to turn off defaults and use a similar to default flag but with raw-window-handle v0.5 as dep.
> Feat: Optional raw window handle 0.5 dep

- README.md
When using glfw-rs with other graphical apis, things can conflict, causing confusion. This adds a note to suggest a fix for this, and it's restrictions.
see gfx-rs/wgpu#5823 and https://github.com/PistonDevelopers/glfw-rs/pull/555#issuecomment-1908198564
> Add a note on glfw-rs with other graphical apis

- Cargo.toml
- examples/vulkan.rs
- src/ffi/mod.rs
- src/lib.rs
- Updated ash dependency from 0.37.2 -> 0.38
- The only required library change was `vk::AllocationCallbacks`, which now needs a lifetime
- Fixed the Vulkan example to reflect the new ash syntax.
> Update ash version and fix examples

- Cargo.toml
- src/lib.rs
This PR adds a `serde` feature to the crate. This feature is off by default, but if enabled derives `Serialize` and `Deserialize` on the majority of glfw's structs.
This allows - for example - storing `glfw::Key` in a config file for keybindings.
> feat: add serde feature
