PistonDevelopers/glfw-rs

README.md

Some variables need to be mutable, otherwise this code doesn't compile.

fixed window and events

---

Cargo.toml

Update for crates.io

---

examples/clipboard.rs
examples/cursor.rs
examples/defaults.rs
examples/error.rs
examples/events.rs
examples/modes.rs
examples/monitors.rs
examples/render_task.rs
examples/title.rs
examples/window.rs
src/lib.rs

Fix unwrap() in examples

---

.travis.yml
README.md
src/ffi/link.rs
src/ffi/mod.rs
src/lib.rs

Add glfw 3.1 bindings and expose new window hints

---

Cargo.toml
examples/events.rs
src/lib.rs

Update to latest rustc

---

src/lib.rs

Version of rustc: rustc 1.0.0-nightly (199bdcfef 2015-03-26).
Fix #302.

Update to the last rust-nightly.

---

src/lib.rs

This commit fixes https://github.com/bjz/glfw-rs/issues/309. I put some TODO-comments near the changes to remind that they can be (mostly) reverted when or if the two features get stable.

Make the library compile on Rust 1.0.0-beta.

---

Cargo.toml
src/lib.rs

Closes https://github.com/bjz/glfw-rs/issues/317
* Bump to 0.1.0

Remove conflicting `Debug` impl on `Modifiers`

---

Cargo.toml

Lock dependencies

---

Cargo.toml

Should be published after #326

Bump version to 0.2, and upgrade libc to 0.2

---

Cargo.toml
src/ffi/mod.rs

- Bumped to 0.3.0
- Use version on glfw-sys

Updated crates.io

---

src/lib.rs

Fixed sample for key polling.

---

Cargo.toml
src/lib.rs

Updated bitflags

---

Cargo.toml
src/lib.rs

Closes https://github.com/PistonDevelopers/glfw-rs/issues/346
- Bumped to 0.7.0

Hide `Window::ptr`

---

.travis.yml
Cargo.toml
src/ffi/link.rs

Also bump glfw-sys dependency to 3.2
Also update travis script to get newer CMake so GLFW can actually build.

Make sure user32 is linked on Windows

---

src/lib.rs

Came across a need for this while incorporating glfw errors into my own.

Implement std::error::Error (and Display) for Error and InitError

---

Cargo.toml

Published 0.14.0

---

src/ffi/mod.rs

Removed TODO comments for already implemented items

---

Cargo.toml
src/lib.rs

Published 0.17.0

---

Cargo.toml

Published 0.18.0

---

Cargo.toml

Published 0.21.0

---

Cargo.toml
src/lib.rs

- Added `pub` to `from_i32` methods

Published 0.29.0

---

Cargo.toml
examples/multiwindow.rs
examples/raw_window_handle.rs
src/ffi/mod.rs
src/lib.rs

Hi, these are some preliminary patches to grant basic wayland support. WIP

wayland patches

---

README.md

Closes https://github.com/PistonDevelopers/glfw-rs/issues/449

Use crates.io in README

---

Cargo.toml

Closes https://github.com/PistonDevelopers/glfw-rs/issues/448

Added minimum Rust version

---

Cargo.toml

- Removed semver meta data
- Removed patch

Fixed Cargo warnings

---

src/lib.rs

Closes https://github.com/PistonDevelopers/glfw-rs/issues/473

Protect Glfw against sending to another thread

---

.travis.yml
Cargo.toml

This PR fixes a bug #514, which I introduced in a previous PR #507.

Making X11 the default again.

---

src/lib.rs

Added `ThreadSafeWindow` and `ThreadSafeGlfw` struct wrappers for `Window` and `Glfw` which contain only thread-safe glfw functions and can be shared between threads. This closes #386 , closes #238

Added ThreadSafeWindow and ThreadSafeGlfw struct wrappers

---

src/callbacks.rs
src/lib.rs

Now `set_error_callback()`, `set_monitor_callback()` and `set_joystick_callback()` accept `FnMut`'s as arguments as opposed to having to initialize a struct with a function and user data. They now also have corresponding unset functions: `unset_error_callback()`, `unset_monitor_callback()` and `unset_joystick_callback()`.

Improved error, monitor and joystick callbacks

---

src/lib.rs

Fixes #560 . This is a breaking change

Safe monitor implementation

---

Cargo.toml

Published 0.60.0
